// const catBreed = [
//   'Kitten',
//   'Tabby',
//   'Bengal',
//   'Siamese',
//   'Norwegian Forest Cat',
//   'Maine Coon',
//   'British Shorthair',
//   'Puma',
//   'Canadian Lynx',
//   'Savannah',
//   'Persian cat',
//   'Caracal',
//   'Courgar',
//   'Leopard',
//   'Abyssinian',
//   'Scottish Fold',
//   'Panther',
//   'Burmese cat',
// ]

const countries = [
  { country: 'United Kingdom', regionCode: 'GB' },
  { country: 'Ukraine', regionCode: 'UA' },
  { country: 'Germany', regionCode: 'DE' },
  { country: 'Turkey', regionCode: 'TR' },
  { country: 'South Africa', regionCode: 'ZA' },
  { country: 'India', regionCode: 'IN' },
  { country: 'Ireland', regionCode: 'IE' },
  { country: 'Japan', regionCode: 'JP' },
  { country: 'Singapore', regionCode: 'SG' },
  { country: 'Hong Kong', regionCode: 'HK' },
  { country: 'United States', regionCode: 'US' },
  { country: 'Canada', regionCode: 'CA' },
  { country: 'Peru', regionCode: 'PE' },
  { country: 'Chile', regionCode: 'CL' },
  { country: 'Bolivia', regionCode: 'BO' },
  { country: 'Australia', regionCode: 'AU' },
  { country: 'New Zealand', regionCode: 'NZ' },
  { country: 'Kazakhstan', regionCode: 'KZ' },
]

export default countries
